#!/usr/bin/env python3
import csv,os,re,sys
sys.path.insert(0,os.path.dirname(__file__)); from schema import *
D=sys.argv[1] if len(sys.argv)>1 else os.path.join(os.path.dirname(__file__),'..','data'); E='RR2022W'; DATE='2026-09-22'
def sec(s):a=list(map(int,s.split(':')));return a[-2]*60+a[-1]
def blank(f):return {k:'' for k in f}
def app(fn,f,rows):
 with open(os.path.join(D,fn),'a',newline='',encoding='utf-8') as x:csv.DictWriter(x,fieldnames=f).writerows(rows)
sources=[['S243','WWE.com — Ronda Rousey wins the 2022 Women’s Royal Rumble','official_wwe','https://www.wwe.com/shows/royalrumble/2022/30-woman-royal-rumble-match-results',1,'WWE / official sources',DATE,'Primary entrant, eliminator and survival-time table.'],['S244','Wikipedia — Royal Rumble (2022), women’s entrances/eliminations','event_database','https://en.wikipedia.org/wiki/Royal_Rumble_(2022)',8,'Reference cross-check',DATE,'Cross-check for elimination order, duration and final sequence.']]
bio={
'Melina':('melina','Melina Nava Perez','1979-03-09','Los Angeles, California, United States','American','2000','Melina','https://www.wwe.com/superstars/melina'),
'Aliyah':('aliyah','Nhooph Al-Areebi','1994-11-23','Toronto, Ontario, Canada','Canadian','2013','Aliyah','https://en.wikipedia.org/wiki/Aliyah_(wrestler)'),
'Cameron':('cameron','Ariane Andrew','1987-11-03','Atlanta, Georgia, United States','American','2011','Cameron;Ariane Andrew','https://en.wikipedia.org/wiki/Cameron_(wrestler)'),
'Ivory':('ivory','Lisa Mary Moretti','1961-11-26','Los Angeles, California, United States','American','1986','Ivory;Tina Ferrari','https://en.wikipedia.org/wiki/Ivory_(wrestler)'),
'Summer Rae':('summer-rae','Danielle Moinet','1983-11-28','Manhasset, New York, United States','American','2011','Summer Rae','https://en.wikipedia.org/wiki/Summer_Rae'),
'Ronda Rousey':('ronda-rousey','Ronda Jean Rousey','1987-02-01','Riverside, California, United States','American','2018','Ronda Rousey','https://en.wikipedia.org/wiki/Ronda_Rousey')}
for i,(n,b) in enumerate(bio.items(),245):sources.append([f'S{i}',f'Dedicated biography — {n}','biography',b[-1],7,'Dedicated biography source',DATE,f'Person-specific biography lookup for {n}.'])
with open(os.path.join(D,'sources.csv'),'a',newline='',encoding='utf-8') as f:csv.writer(f).writerows(sources)
wr=list(csv.DictReader(open(os.path.join(D,'wrestlers.csv'),encoding='utf-8'))); by={r['ring_name'].lower():r['wrestler_id'] for r in wr}; al={a.strip().lower():r['wrestler_id'] for r in wr for a in r['aliases_ring_names'].split(';') if a.strip()};new=[]
for i,(n,b) in enumerate(bio.items(),245):
 if n.lower() not in by and n.lower() not in al:
  wi,real,dob,bp,nat,debut,als,url=b;r=blank(WRESTLERS_FIELDS);r.update(wrestler_id=wi,ring_name=n,real_name=real,real_name_status='CONFIRMED',gender='F',dob=dob,dob_status='CONFIRMED',birthplace=bp,birthplace_status='CONFIRMED',nationality=nat,debut_year_company=debut,aliases_ring_names=als,notes=f'Added for {E}; individually researched.',source_ids=f'S{i}');new.append(r);by[n.lower()]=wi
app('wrestlers.csv',WRESTLERS_FIELDS,new); ids={**by,**al};ids.update({'queen zelina':'zelina-vega','nikki a.s.h.':'nikki-cross','mighty molly':'molly-holly','shotzi':'shotzi-blackheart'})
names=['Sasha Banks','Melina','Tamina','Kelly Kelly','Aliyah','Liv Morgan','Queen Zelina','Bianca Belair','Dana Brooke','Michelle McCool','Sonya Deville','Natalya','Cameron','Naomi','Carmella','Rhea Ripley','Charlotte Flair','Ivory','Brie Bella','Mickie James','Alicia Fox','Nikki A.S.H.','Summer Rae','Nikki Bella','Sarah Logan','Lita','Mighty Molly','Ronda Rousey','Shotzi','Shayna Baszler'];wid={n:ids[n.lower()] for n in names}
times=['09:44','00:53','16:41','01:05','22:50','37:20','17:25','47:30','02:12','20:50','02:00','36:17','00:51','07:18','00:50','30:59','31:23','00:25','19:21','11:40','06:30','12:13','00:52','08:40','00:43','10:21','00:20','10:16','02:56','05:31']; order=[3,1,5,2,10,17,9,28,4,13,7,24,6,11,8,26,29,12,22,18,15,20,14,21,16,25,19,'',23,27]
eb={'Sasha Banks':['Queen Zelina'],'Melina':['Sasha Banks'],'Tamina':['Natalya'],'Kelly Kelly':['Sasha Banks'],'Aliyah':['Charlotte Flair'],'Liv Morgan':['Brie Bella'],'Queen Zelina':['Rhea Ripley'],'Bianca Belair':['Charlotte Flair'],'Dana Brooke':['Michelle McCool'],'Michelle McCool':['Mickie James'],'Sonya Deville':['Naomi'],'Natalya':['Bianca Belair'],'Cameron':['Sonya Deville'],'Naomi':['Sonya Deville'],'Carmella':['Rhea Ripley'],'Rhea Ripley':['Charlotte Flair'],'Charlotte Flair':['Ronda Rousey'],'Ivory':['Rhea Ripley'],'Brie Bella':['Ronda Rousey'],'Mickie James':['Lita'],'Alicia Fox':['Nikki Bella'],'Nikki A.S.H.':['Ronda Rousey'],'Summer Rae':['Natalya'],'Nikki Bella':['Brie Bella'],'Sarah Logan':['Brie Bella','Nikki Bella'],'Lita':['Charlotte Flair'],'Mighty Molly':['Nikki A.S.H.'],'Shotzi':['Ronda Rousey'],'Shayna Baszler':['Charlotte Flair']}
erows=[];ents=[]
for i,n in enumerate(names):
 es=eb.get(n,[]);shared=len(es)>1;win=n=='Ronda Rousey'
 for e in es:
  r=blank(ELIMINATIONS_FIELDS);r.update(event_id=E,order_in_match=order[i],eliminated_wrestler_id=wid[n],eliminator_wrestler_id=wid[e],assisting_wrestler_ids=';'.join(wid[x] for x in es if x!=e) if shared else '',entry_number_of_eliminated=i+1,entry_number_of_eliminator=names.index(e)+1,elimination_type='over_top_rope',is_solo='FALSE' if shared else 'TRUE',is_shared='TRUE' if shared else 'FALSE',is_accidental='FALSE',is_self_elimination='FALSE',is_disputed='FALSE',simultaneous_group_id=f'{E}-E{order[i]}' if shared else '',data_quality_status='CONFIRMED',source_ids='S243;S244');erows.append(r)
 r=blank(ENTRANTS_FIELDS);r.update(event_id=E,wrestler_id=wid[n],match_id=E,entry_number=i+1,entry_number_status='CONFIRMED',ring_name_at_time=n,name_displayed_at_event=n,elim_number=order[i],elim_number_status='' if win else 'CONFIRMED',eliminated_by_ids=';'.join(wid[x] for x in es),ring_time=times[i],ring_time_seconds=sec(times[i]),ring_time_status='CONFIRMED',self_eliminated='FALSE',is_winner='TRUE' if win else 'FALSE',is_runner_up='TRUE' if n=='Charlotte Flair' else 'FALSE',is_final_two='TRUE' if n in {'Ronda Rousey','Charlotte Flair'} else 'FALSE',is_final_three='TRUE' if n in {'Ronda Rousey','Charlotte Flair','Bianca Belair'} else 'FALSE',is_final_four='TRUE' if n in {'Ronda Rousey','Charlotte Flair','Bianca Belair','Shayna Baszler'} else 'FALSE',surprise_entrant='TRUE' if n in {'Melina','Cameron','Ivory','Summer Rae','Sarah Logan','Mighty Molly','Ronda Rousey'} else 'FALSE',legend_returning='TRUE' if n in {'Melina','Ivory','Mighty Molly'} else 'FALSE',celebrity_entrant='FALSE',data_quality_status='CONFIRMED',source_ids='S243;S244');ents.append(r)
cr={}
for r in erows:cr.setdefault(r['eliminator_wrestler_id'],[]).append(r['eliminated_wrestler_id'])
for r in ents:
 c=cr.get(r['wrestler_id'],[]);r['wrestlers_eliminated_count']=len(c);r['wrestlers_eliminated_ids']=';'.join(c);r['solo_eliminations_count']=sum(x['eliminator_wrestler_id']==r['wrestler_id'] and x['is_solo']=='TRUE' for x in erows);r['assisted_eliminations_count']=sum(x['eliminator_wrestler_id']==r['wrestler_id'] and x['is_shared']=='TRUE' for x in erows)
app('entrants.csv',ENTRANTS_FIELDS,ents);app('eliminations.csv',ELIMINATIONS_FIELDS,erows)
flags=[['F424',E,'entrants','queen-zelina;nikki-a-s-h;mighty-molly;shotzi','wrestler_id','name_stable_id','Queen Zelina reuses zelina-vega, Nikki A.S.H. reuses nikki-cross, Mighty Molly reuses molly-holly and Shotzi reuses shotzi-blackheart. This follows the established name-stable-ID precedent: presentation changes do not create duplicate people; unlike a genuinely new performer such as Omos in RR2021M, these are already represented wrestlers.','S243;S244','resolved',DATE],['F425',E,'eliminations','naomi','eliminated_by_ids','official_post_elimination_interference','WWE officially lists Sonya Deville as Naomi’s eliminator even though Deville had already been eliminated. This follows the Omos RR2021M precedent because the official WWE results explicitly assign the elimination credit; it differs from narrative-only interference such as Authors of Pain in RR2020M, where WWE did not list them as eliminators of record.','S243;S244','resolved',DATE]]
with open(os.path.join(D,'flags.csv'),'a',newline='',encoding='utf-8') as f:csv.writer(f).writerows(flags)
m=[]
for mid,title,p,desc in [('NM100','Ronda Rousey returns and wins',['Ronda Rousey'],'Rousey returned at No. 28 and won.'),('NM101','Mickie James enters as Impact champion',['Mickie James'],'WWE acknowledged Mickie James as reigning Impact Knockouts World Champion.'),('NM102','Sonya Deville eliminates Naomi after elimination',['Sonya Deville','Naomi'],'Deville returned after her own elimination and WWE officially credited her with eliminating Naomi.'),('NM103','Mighty Molly surprise return',['Mighty Molly'],'Molly Holly entered under her Mighty Molly presentation.')]:
 r=blank(NOTABLE_MOMENTS_FIELDS);r.update(moment_id=mid,event_id=E,wrestler_ids_involved=';'.join(wid[x] for x in p),category='notable',title=title,description=desc,data_quality_status='CONFIRMED',source_ids='S243;S244');m.append(r)
app('notable_moments.csv',NOTABLE_MOMENTS_FIELDS,m)
ev=blank(EVENTS_FIELDS);ev.update(event_id=E,event_name='Royal Rumble 2022',match_name='Royal Rumble Match',match_type="Women's",event_date='2022-01-29',venue="The Dome at America's Center",city_region='St. Louis, Missouri',country='United States',entrant_count=len(ents),duration_total='59:40',duration_status='CONFIRMED',winner_id=wid['Ronda Rousey'],runner_up_id=wid['Charlotte Flair'],final_two_ids=wid['Ronda Rousey']+';'+wid['Charlotte Flair'],final_three_ids=';'.join(wid[x] for x in ['Ronda Rousey','Charlotte Flair','Bianca Belair']),final_four_ids=';'.join(wid[x] for x in ['Ronda Rousey','Charlotte Flair','Bianca Belair','Shayna Baszler']),first_entrant_id=wid['Sasha Banks'],second_entrant_id=wid['Melina'],final_entrant_id=wid['Shayna Baszler'],first_elimination_id=wid['Melina'],last_elimination_before_winner_id=wid['Charlotte Flair'],eliminations_count=len({r['eliminated_wrestler_id'] for r in erows}),eliminators_count=len({r['eliminator_wrestler_id'] for r in erows}),surprise_entrants_count=sum(r['surprise_entrant']=='TRUE' for r in ents),champions_in_field_count='',hall_of_famers_in_field_count='',tag_teams_count='',factions_count='',title_on_the_line='FALSE',championship_implications='Winner earned a women’s world championship match at WrestleMania 38.',winners_reward='Women’s world championship match at WrestleMania 38.',data_quality_status='CONFIRMED',source_ids='S243;S244')
app('events.csv',EVENTS_FIELDS,[ev]);checks={'entrant_count':len(ents),'eliminations_count':len({r['eliminated_wrestler_id'] for r in erows}),'eliminators_count':len({r['eliminator_wrestler_id'] for r in erows}),'surprise_entrants_count':sum(r['surprise_entrant']=='TRUE' for r in ents)}
print('SELF-CHECK RR2022W');
for k,v in checks.items():print(f'{k}: declared={ev[k]} recomputed={v} match={str(ev[k])==str(v)}')
print(f'RR2022W build complete: {len(new)} new wrestlers, {len(ents)} entrants, {len(erows)} elimination-credit rows, {len(sources)} sources, {len(flags)} flags, {len(m)} moments.')
