#!/usr/bin/env python3
"""Build RR2021W from live-web researched sources. Unknown fields stay blank."""
import csv, os, re, sys
sys.path.insert(0,os.path.dirname(__file__))
from schema import WRESTLERS_FIELDS,EVENTS_FIELDS,ENTRANTS_FIELDS,ELIMINATIONS_FIELDS,SOURCES_FIELDS,FLAGS_FIELDS,NOTABLE_MOMENTS_FIELDS
DATA_DIR=sys.argv[1] if len(sys.argv)>1 else os.path.join(os.path.dirname(__file__),'..','data')
EVENT_ID='RR2021W'; BUILD_DATE='2026-09-22'
def sec(s): a=list(map(int,s.split(':'))); return a[0]*60+a[1]
def slug(s): return re.sub(r'[^a-z0-9]+','-',s.lower()).strip('-')
# IDs recomputed immediately before authoring this build: S224, F418, NM92.
sources=[
('S224','WWE.com — Bianca Belair won the 2021 Royal Rumble Match','official_wwe','https://www.wwe.com/shows/royalrumble/01-31-2021/womens-royal-rumble-match-results',1,'WWE / official sources',BUILD_DATE,'Primary source: entrants, official survival times, eliminator credits, surprise entrants and match narrative.'),
('S225','Cagematch — WWE Royal Rumble 2021','event_database','https://www.cagematch.net/?id=1&nr=299033',4,'Cagematch',BUILD_DATE,'Cross-check: entrant order, chronological elimination order, eliminator credits and total match duration.'),
('S226','411Mania — 2021 Women’s Royal Rumble Stats','reputable_wrestling_press','https://411mania.com/wrestling/2021-womens-royal-rumble-stats-most-eliminations-order-entrants-more/',7,'Wrestling Observer/reputable wrestling pubs',BUILD_DATE,'Independent cross-check for entrance order, elimination order and credits.'),
('S227','Cageside Seats — Complete survival times for 2021 women’s Royal Rumble','contemporary_publication','https://www.cagesideseats.com/wwe/2021/2/1/22260615/wwe-royal-rumble-2021-womens-survival-times-complete-list',9,'Contemporary wrestling publication',BUILD_DATE,'Independent footage-timed survival-time cross-check.'),
('S228','WWE.com — Full Royal Rumble 2021 results','official_wwe','https://www.wwe.com/shows/royalrumble/article/royal-rumble-results',1,'WWE / official sources',BUILD_DATE,'Confirms Nia Jax & Shayna Baszler won the WWE Women’s Tag Team Championship earlier on the same card.'),]
with open(os.path.join(DATA_DIR,'sources.csv'),'a',newline='',encoding='utf-8') as f: csv.writer(f).writerows(sources)
names=['Bayley','Naomi','Bianca Belair','Billie Kay','Shotzi Blackheart','Shayna Baszler','Toni Storm','Jillian Hall','Ruby Riott','Victoria','Peyton Royce','Santana Garrett','Liv Morgan','Rhea Ripley','Charlotte Flair','Dana Brooke','Torrie Wilson','Lacey Evans','Mickie James','Nikki Cross','Alicia Fox','Mandy Rose','Dakota Kai','Carmella','Tamina','Lana','Alexa Bliss','Ember Moon','Nia Jax','Natalya']; entry={n:i+1 for i,n in enumerate(names)}
existing={r['ring_name']:r['wrestler_id'] for r in csv.DictReader(open(os.path.join(DATA_DIR,'wrestlers.csv'),encoding='utf-8'))}
new=['Jillian Hall','Victoria','Santana Garrett']
with open(os.path.join(DATA_DIR,'wrestlers.csv'),'a',newline='',encoding='utf-8') as f:
 w=csv.DictWriter(f,fieldnames=WRESTLERS_FIELDS)
 bio={
 'Jillian Hall':{'real_name':'Jillian Faye Hall (née Fletcher)','real_name_status':'CONFIRMED','dob':'1980-09-06','dob_status':'CONFIRMED','birthplace':'Ashland, Kentucky, United States','birthplace_status':'CONFIRMED','nationality':'American','debut_year_company':'1998 — independent circuit','aliases_ring_names':'Jillian;Macaela Mercedes','source_ids':'S224;S225;S229'},
 'Victoria':{'real_name':'Lisa Marie Varon (born Sole)','real_name_status':'CONFIRMED','dob':'1971-02-10','dob_status':'CONFIRMED','birthplace':'San Bernardino, California, United States','birthplace_status':'CONFIRMED','nationality':'American','debut_year_company':'2000','aliases_ring_names':'Victoria;Tara;Lisa Marie Varon;Queen Victoria','source_ids':'S224;S225;S230'},
 'Santana Garrett':{'real_name':'Santana Garrett','real_name_status':'CONFIRMED','dob':'1988-05-22','dob_status':'CONFIRMED','birthplace':'Ocala, Florida, United States','birthplace_status':'CONFIRMED','nationality':'American','debut_year_company':'2009 — independent circuit','aliases_ring_names':'Santana Garrett;Brittany;Santana;Santana G','source_ids':'S224;S225;S231'}}
 for n in new:
  row={k:'' for k in WRESTLERS_FIELDS}; row.update({'wrestler_id':slug(n),'ring_name':n,'gender':'F','notes':'Added for RR2021W; biography individually researched from a dedicated wrestler-profile source.'}); row.update(bio[n]); w.writerow(row); existing[n]=slug(n)
wid={n:existing[n] for n in names}
times={'Bayley':'29:08','Naomi':'47:40','Bianca Belair':'56:52','Billie Kay':'8:11','Shotzi Blackheart':'2:46','Shayna Baszler':'41:46','Toni Storm':'11:21','Jillian Hall':'8:03','Ruby Riott':'10:53','Victoria':'7:15','Peyton Royce':'13:40','Santana Garrett':'4:32','Liv Morgan':'6:37','Rhea Ripley':'39:06','Charlotte Flair':'33:47','Dana Brooke':'2:58','Torrie Wilson':'3:59','Lacey Evans':'19:21','Mickie James':'7:20','Nikki Cross':'7:37','Alicia Fox':'1:48','Mandy Rose':'3:49','Dakota Kai':'2:06','Carmella':'0:47','Tamina':'8:31','Lana':'9:58','Alexa Bliss':'1:02','Ember Moon':'1:51','Nia Jax':'2:44','Natalya':'2:00'}
order=['Shotzi Blackheart','Jillian Hall','Billie Kay','Toni Storm','Victoria','Santana Garrett','Ruby Riott','Liv Morgan','Dana Brooke','Peyton Royce','Torrie Wilson','Bayley','Alicia Fox','Mickie James','Dakota Kai','Mandy Rose','Nikki Cross','Carmella','Alexa Bliss','Lacey Evans','Ember Moon','Naomi','Tamina','Shayna Baszler','Nia Jax','Lana','Natalya','Charlotte Flair','Rhea Ripley']; eno={n:i+1 for i,n in enumerate(order)}
elims={'Shotzi Blackheart':['Shayna Baszler'],'Jillian Hall':['Billie Kay'],'Billie Kay':['Liv Morgan','Ruby Riott'],'Toni Storm':['Rhea Ripley'],'Victoria':['Shayna Baszler'],'Santana Garrett':['Rhea Ripley'],'Ruby Riott':['Bayley'],'Liv Morgan':['Bayley','Peyton Royce'],'Dana Brooke':['Rhea Ripley'],'Peyton Royce':['Charlotte Flair'],'Torrie Wilson':['Shayna Baszler'],'Bayley':['Bianca Belair'],'Alicia Fox':['Mandy Rose'],'Mickie James':['Lacey Evans'],'Dakota Kai':['Rhea Ripley'],'Mandy Rose':['Rhea Ripley'],'Nikki Cross':['Carmella'],'Carmella':['Tamina'],'Alexa Bliss':['Rhea Ripley'],'Lacey Evans':['Shayna Baszler'],'Ember Moon':['Nia Jax'],'Naomi':['Shayna Baszler','Nia Jax'],'Tamina':['Shayna Baszler','Nia Jax'],'Shayna Baszler':['Nia Jax'],'Nia Jax':['Lana'],'Lana':['Natalya'],'Natalya':['Bianca Belair'],'Charlotte Flair':['Bianca Belair','Rhea Ripley'],'Rhea Ripley':['Bianca Belair']}
conflict_credit={'Liv Morgan','Carmella'}
elimrows=[]; entrants=[]
for n in names:
 win=n=='Bianca Belair'; es=elims.get(n,[]); shared=len(es)>1
 for e in es:
  note=''
  if n=='Liv Morgan': note='WWE credits Bayley & Peyton Royce; Cagematch/411Mania credit Peyton Royce alone. WWE tier-1 credit stored; see F419.'
  if n=='Carmella': note='WWE credits Tamina before Tamina officially entered; Cagematch credits Reginald. WWE tier-1 credit stored; see F419.'
  r={k:'' for k in ELIMINATIONS_FIELDS}; r.update({'event_id':EVENT_ID,'order_in_match':eno[n],'eliminated_wrestler_id':wid[n],'eliminator_wrestler_id':wid[e],'assisting_wrestler_ids':';'.join(wid[x] for x in es if x!=e) if shared else '','entry_number_of_eliminated':entry[n],'entry_number_of_eliminator':entry.get(e,''),'elimination_type':'over_top_rope','is_solo':'FALSE' if shared else 'TRUE','is_shared':'TRUE' if shared else 'FALSE','is_accidental':'FALSE','is_self_elimination':'FALSE','is_disputed':'TRUE' if n in conflict_credit else 'FALSE','simultaneous_group_id':f'RR2021W-E{eno[n]}' if shared else '','data_quality_status':'CONFLICTING' if n in conflict_credit else 'CONFIRMED','source_ids':'S224;S225;S226','notes':note}); elimrows.append(r)
 er={k:'' for k in ENTRANTS_FIELDS}; er.update({'event_id':EVENT_ID,'wrestler_id':wid[n],'match_id':EVENT_ID,'entry_number':entry[n],'entry_number_status':'CONFIRMED','ring_name_at_time':n,'name_displayed_at_event':n,'is_rumble_debut':'TRUE' if n in new else '','elim_number':'' if win else eno[n],'elim_number_status':'' if win else 'CONFIRMED','eliminated_by_ids':';'.join(wid[x] for x in es),'ring_time':times[n],'ring_time_seconds':sec(times[n]),'ring_time_status':'CONFLICTING','self_eliminated':'FALSE','is_winner':'TRUE' if win else 'FALSE','is_runner_up':'TRUE' if n=='Rhea Ripley' else 'FALSE','is_final_two':'TRUE' if n in {'Bianca Belair','Rhea Ripley'} else 'FALSE','is_final_three':'TRUE' if n in {'Bianca Belair','Rhea Ripley','Charlotte Flair'} else 'FALSE','is_final_four':'TRUE' if n in {'Bianca Belair','Rhea Ripley','Charlotte Flair','Natalya'} else 'FALSE','surprise_entrant':'TRUE' if n in {'Jillian Hall','Victoria','Torrie Wilson','Toni Storm','Ember Moon','Lana'} else 'FALSE','legend_returning':'TRUE' if n in {'Jillian Hall','Victoria','Torrie Wilson'} else 'FALSE','celebrity_entrant':'FALSE','wrestled_earlier_on_card':'TRUE' if n in {'Shayna Baszler','Nia Jax','Charlotte Flair'} else 'FALSE','was_hof_member_at_time':'TRUE' if n=='Torrie Wilson' else 'FALSE','current_champion_title':'WWE Women’s Tag Team Championship' if n in {'Shayna Baszler','Nia Jax'} else '','championship_level':'Tag Team' if n in {'Shayna Baszler','Nia Jax'} else '','championship_partner':wid['Nia Jax'] if n=='Shayna Baszler' else (wid['Shayna Baszler'] if n=='Nia Jax' else ''),'title_won_date':'2021-01-31' if n in {'Shayna Baszler','Nia Jax'} else '','days_into_reign_at_event':0 if n in {'Shayna Baszler','Nia Jax'} else '','title_defended_same_card':'FALSE','title_lost_same_card':'FALSE','data_quality_status':'CONFLICTING' if n in conflict_credit else 'CONFIRMED','source_ids':'S224;S225;S226;S227','notes':''}); entrants.append(er)
credit={}
for r in elimrows: credit.setdefault(r['eliminator_wrestler_id'],[]).append(r['eliminated_wrestler_id'])
for r in entrants:
 c=credit.get(r['wrestler_id'],[]); r['wrestlers_eliminated_count']=len(c); r['wrestlers_eliminated_ids']=';'.join(c); r['solo_eliminations_count']=sum(x['eliminator_wrestler_id']==r['wrestler_id'] and x['is_solo']=='TRUE' for x in elimrows); r['assisted_eliminations_count']=sum(x['eliminator_wrestler_id']==r['wrestler_id'] and x['is_shared']=='TRUE' for x in elimrows)
with open(os.path.join(DATA_DIR,'entrants.csv'),'a',newline='',encoding='utf-8') as f: csv.DictWriter(f,fieldnames=ENTRANTS_FIELDS).writerows(entrants)
with open(os.path.join(DATA_DIR,'eliminations.csv'),'a',newline='',encoding='utf-8') as f: csv.DictWriter(f,fieldnames=ELIMINATIONS_FIELDS).writerows(elimrows)
flags=[
('F418',EVENT_ID,'wrestlers','jillian-hall;victoria;santana-garrett','bio_fields','unverified','These three entrant records were genuinely new to wrestlers.csv. Only identity/participation was established in this build; unsupported biographical fields were deliberately left blank.','S224;S225','open',BUILD_DATE),
('F419',EVENT_ID,'eliminations','liv-morgan;carmella','eliminated_by_ids','conflicting_sources','Eliminator-credit conflicts: WWE credits Liv Morgan to Bayley & Peyton Royce while Cagematch/411Mania credit Peyton alone. WWE credits Carmella to Tamina before Tamina entered, while Cagematch credits Reginald. Higher-tier WWE credits are stored.','S224;S225;S226','open',BUILD_DATE),
('F420',EVENT_ID,'entrants','multiple','ring_time','conflicting_sources','WWE official survival times differ from Cageside Seats footage-timed values for multiple entrants (usually by one second, with larger differences for some). WWE tier-1 values are stored and ring_time_status is CONFLICTING rather than silently reconciling them.','S224;S227','open',BUILD_DATE),
('F421',EVENT_ID,'entrants','all','elimination_clock_time','unverified','Cagematch supplies chronological match-clock elimination timestamps, but clock fields are left blank because this build did not establish a second independent source using the same clock convention for all eliminations.','S225','open',BUILD_DATE)]
with open(os.path.join(DATA_DIR,'flags.csv'),'a',newline='',encoding='utf-8') as f: csv.writer(f).writerows(flags)
moms=[
{'moment_id':'NM92','event_id':EVENT_ID,'wrestler_ids_involved':wid['Bianca Belair'],'category':'record','title':'Bianca Belair wins from No. 3','description':'Bianca Belair entered at No. 3 and won, with WWE listing 56:52 of survival time.','data_quality_status':'CONFIRMED','source_ids':'S224;S225','notes':''},
{'moment_id':'NM93','event_id':EVENT_ID,'wrestler_ids_involved':wid['Rhea Ripley'],'category':'record','title':'Rhea Ripley records seven eliminations','description':'WWE credits Rhea Ripley with a match-high seven eliminations.','data_quality_status':'CONFIRMED','source_ids':'S224;S226','notes':''},
{'moment_id':'NM94','event_id':EVENT_ID,'wrestler_ids_involved':wid['Alicia Fox'],'category':'storyline_moment','title':'Alicia Fox briefly wins the 24/7 Championship','description':'During the Royal Rumble, Alicia Fox pinned R-Truth to win the 24/7 Championship before Truth regained it moments later.','data_quality_status':'PROBABLE','source_ids':'S224','notes':''},
{'moment_id':'NM95','event_id':EVENT_ID,'wrestler_ids_involved':wid['Carmella']+';'+wid['Tamina'],'category':'controversy','title':'Official Carmella eliminator credit differs by source','description':'WWE lists Tamina as Carmella’s eliminator before Tamina entered the match, while Cagematch lists Reginald; the structured elimination follows WWE’s higher-tier official result.','data_quality_status':'CONFLICTING','source_ids':'S224;S225','notes':'See F419.'}]
with open(os.path.join(DATA_DIR,'notable_moments.csv'),'a',newline='',encoding='utf-8') as f: csv.DictWriter(f,fieldnames=NOTABLE_MOMENTS_FIELDS).writerows(moms)
ev={k:'' for k in EVENTS_FIELDS}; ev.update({'event_id':EVENT_ID,'event_name':'Royal Rumble 2021','match_name':'Royal Rumble Match','match_type':"Women's",'event_date':'2021-01-31','venue':'WWE ThunderDome at Tropicana Field','city_region':'St. Petersburg, Florida','country':'United States','attendance_official':0,'attendance_reported':0,'entry_interval_seconds':90,'entrant_count':30,'duration_total':'58:48','duration_status':'PROBABLE','winner_id':wid['Bianca Belair'],'runner_up_id':wid['Rhea Ripley'],'final_two_ids':wid['Bianca Belair']+';'+wid['Rhea Ripley'],'final_three_ids':wid['Bianca Belair']+';'+wid['Rhea Ripley']+';'+wid['Charlotte Flair'],'final_four_ids':wid['Bianca Belair']+';'+wid['Rhea Ripley']+';'+wid['Charlotte Flair']+';'+wid['Natalya'],'first_entrant_id':wid['Bayley'],'second_entrant_id':wid['Naomi'],'final_entrant_id':wid['Natalya'],'first_elimination_id':wid['Shotzi Blackheart'],'last_elimination_before_winner_id':wid['Rhea Ripley'],'eliminations_count':29,'eliminators_count':len({r['eliminator_wrestler_id'] for r in elimrows}),'surprise_entrants_count':6,'champions_in_field_count':2,'hall_of_famers_in_field_count':1,'tag_teams_count':'','factions_count':'','special_rules':'Standard Royal Rumble rules; WWE states a new entrant arrived every 90 seconds. Event held in the WWE ThunderDome without an in-person paying audience.','title_on_the_line':'FALSE','championship_implications':'The winner earned a world championship match at WrestleMania 37.','winners_reward':'A world championship match at WrestleMania 37.','historical_significance':'Bianca Belair won from entry No. 3; WWE described her 56-plus-minute performance as a women’s Royal Rumble longevity record at the time.','notes':'Eliminator-credit conflicts preserved in F419; survival-time source conflicts in F420. tag_teams_count and factions_count are blank because not established to sourcing standard.','data_quality_status':'CONFLICTING','source_ids':'S224;S225;S226;S227;S228'})
with open(os.path.join(DATA_DIR,'events.csv'),'a',newline='',encoding='utf-8') as f: csv.DictWriter(f,fieldnames=EVENTS_FIELDS).writerow(ev)
print(f"2021 Women's build complete: {len(new)} new wrestlers, {30-len(new)} reused wrestler IDs, 30 entrants, {len(elimrows)} elimination-credit rows, {len({r['eliminator_wrestler_id'] for r in elimrows})} distinct eliminators, {len(sources)} sources, {len(flags)} flags, {len(moms)} notable moments.")
